version: '3'
services:
  pyspark_dev_v:
    build:
      context: .
      dockerfile: Jupyter.Dockerfile
    container_name: spark_dev_v
    volumes:
      - '.:/src'
    ports:
      - '8888:8888'
      - '4040:4040'
    restart: on-failure
    env_file:
      - .env
    command: /bin/sh -c "jupyter lab --ip='0.0.0.0' --port=8888 --NotebookApp.token='' --no-browser --allow-root"
    
